### ISSUE TITLE
Default number of instances for Healthwatch Forwarder is 2 not 1

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/docs-pcf-healthwatch#106]
In the table here https://docs.pivotal.io/pcf-healthwatch/1-0/resources.html#requirements
All of the actual (unconfigurable) resource configs for healthwatch:
MySQL is non-updatable, set to 1
Redis is non-updatable, set to 1
Healthwatch Forwarder is non-updatable, set to 2
![screen shot 2018-06-07 at 8 17 04 am](https://user-images.githubusercontent.com/1361223/41105554-3441ae8e-6a2b-11e8-97bd-fd68e536c1df.png)
![screen shot 2018-06-07 at 8 17 10 am](https://user-images.githubusercontent.com/1361223/41105555-34560c30-6a2b-11e8-9c85-8c89204cd038.png)
![screen shot 2018-06-07 at 8 15 18 am](https://user-images.githubusercontent.com/1361223/41105417-f33f306e-6a2a-11e8-8dde-230177b81009.png)

**NOTE** this may only be an issue for an already installed tile. If this is the case, this is a Healthwatch issue, not a docs issue

**Comment by AmberAlston** [comment]
@kcboyle I'm confused. Your screenshots reference an architecture only available in v1.2 but your link is for the very different v1.0 version. v1.2 table looks correct - http://docs.pivotal.io/pcf-healthwatch/1-2/resources.html. v1.0 table linked in issue looks correct for the architecture as it was in v1.0.

**Comment by seviet** [comment]
Closing this since I think it sounds like a versioning issue. @kcboyle reopen if you disagree
