### ISSUE TITLE
1.8 not listed, default on documentation site

### ISSUE THREAD

**Issue by coffee-squirrel** [pivotal-cf/docs-pcf-healthwatch#330]
Given Healthwatch 1.8.0 is currently [the latest release on PivNet](https://network.pivotal.io/products/p-healthwatch) it seems v1.8 should be the default shown for Healthwatch documentation.

* https://docs.pivotal.io/platform/healthwatch/ redirects to https://docs.pivotal.io/platform/healthwatch/1-7/
* v1.8 is not listed in the Healthwatch documentation version dropdown ([it is available](https://docs.pivotal.io/platform/healthwatch/1-8/), albeit still with CHANGEME's)

**Comment by radaeze** [comment]
@coffee-squirrel Thanks for flagging this! All of the issues should now be resolved. The redirect might take a bit to work though if you have it cached.
