### ISSUE TITLE
LDAP Integration with pcf-healthwatch

### ISSUE THREAD

**Issue by Muruganfly03** [pivotal-cf/docs-pcf-healthwatch#331]
Hi Team

       We follow the below procedure to adding access to Healthwatch Portal.

https://docs.pivotal.io/platform/healthwatch/1-8/installing.html#healthwatch-uaa-users

Is there is any way we can integrate with LDAP?

**Comment by jncd** [comment]
Hi @Muruganfly03 
Thank you for logging this issue. I've pinged the Healthwatch engineers a couple of times with your question. (Going forward, if your question is urgent, please contact Support for a faster response.)
