### ISSUE TITLE
UAA Authentication examples

### ISSUE THREAD

**Issue by Houlistonm** [pivotal-cf/docs-pcf-healthwatch#341]
Please an example of roles that a UAA User must possess to be a Grafana Admin.
Better examples with orgs/spaces/users would help the admins to configure the product.

**Comment by Houlistonm** [comment]
To update this request, I've found the mapping of scopes to Grafana roles in the system configuration.
I think the docs should be updated to include how to create the necessary groups.  Our UAA doesn't have a group named healthwatch.edit.

**Comment by cshollingsworth** [comment]
Hi, @Houlistonm !

We've updated the procedure to include creating a user account for the UAA client and adding the correct scope to that user account: https://docs.pivotal.io/healthwatch/2-1/configuring/grafana-authentication.html#create-uaa-client

We hope this helps!
