### ISSUE TITLE
Login steps for LDAP or SAML based UAA

### ISSUE THREAD

**Issue by p-alexisv** [pivotal-cf/docs-pcf-healthwatch#399]
The steps 2.j and 2.k in "Configure the BOSH Deployment Metric Exporter VM" (https://docs.pivotal.io/healthwatch/2-1/configuring/configuring-exporter-tkgi.html#bosh-deployments) won't work if Ops Manager has been switched to LDAP or SAML auth (instead of Internal auth).

The "UAA Admin User Credentials" won't be existing if LDAP or SAML auth is being used.

The workaround for this is the following, which should replace steps 2.j and 2.k if using LDAP/SAML auth:

1) Make sure to provision an admin client as per step 1 in https://docs.pivotal.io/ops-manager/2-10/install/opsmanager-create-bosh-client.html#saml.
2) You should have "Uaa Bosh Client Credentials" added in the list of credentials for Bosh Director. Note down the client username and secret for this particular credential. You should then use this credential to login to the Director UAA instance by running the following command.

`uaac token client get bosh_admin_client -s $UAA-BOSH-CLIENT-SECRET`

**Comment by erabil** [comment]
Thank you for the detailed workaround @p-alexisv! I'll let you know once they're live in the docs.

**Comment by erabil** [comment]
Alright @p-alexisv, there's a whole new section in the docs to address the SAML/LDAP options now: https://docs.pivotal.io/healthwatch/2-1/configuring/configuring-exporter-tkgi.html#create-uaa-client
I hope this helps others!
