### ISSUE TITLE
Service Network Creation

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/docs-pcf-healthwatch#45]
With regard to service network, should this sit in the same dedicated-services-network that the ref arch uses?

https://raw.githubusercontent.com/pivotal-cf/docs-pcf-refarch/master/images/aws-overview-arch.png

For example, in the diagram above, we would have the service network checkbox ticked for dedicated-services.  If you are implying that we need another network to use Health Watch, we should talk to the ref arch and customer0 teams, because it isn't easy to add this after the fact for most customers.

**Comment by ljarzynski** [comment]
@AmberAlston Can you provide guidance on this question? We _think_ it should go on the service network, if available. Should we put any guidance in the healthwatch install docs?

**Comment by agregory999** [comment]
My understanding, having install ref arch on both AWS and GCP, is that the service network as defined, does NOT have the service network checkbox, but only the dedicated-services network does.  This one is really for things like the mysqlv2 dedicated instances and so on.  Aside from this network, it would need to be created.

Curious why it wouldn't just go into the ERT network.  Just an explanation of where it fits into the ref-arch would be great.  And if it needs to change, customer0 pipelines and manual install processes may need to be updated.

_Andrew


Andrew Gregory
Senior Platform Architect, New England
+1 617-529-0749 | agregory@pivotal.io <mailto:agregory@pivotal.io>



Transforming how the world builds software.

**Comment by robertjsullivan** [comment]
The real requirement here is that we need a networks whose IP's are controlled by Bosh and not by OpsManager.  We have a bosh-health-check app that deploys it's own VM periodically to the director that needs a single IP that won't collide with the OpsMan deployed releases.  

In our test environments we've seen OpsMen that had no service networks provided so we were trying to be intentionally vague here.  Perhaps we should change the instructions to something like "Use a service network whose IPs are managed by Bosh and has at least one free IP"

FWIW, the default services network on our Toolsmith's provided GCP envs have the Service Network box selected.

**Comment by AmberAlston** [comment]
Eventually this need to use a service network will go away, because there will be no more worries about IP collision. Right now, that OpsMan work is expected around PCF 2.1. At that point, Healthwatch can eliminate the need for creating/using a service network. Agree with Bob's points on the possible Docs improvement. fyi @vikafed

**Comment by vikafed** [comment]
Closing the issue. The installing.html doc has been clarified.
