### ISSUE TITLE
Healthwatch v2.2.5 released, but release notes aren't published

### ISSUE THREAD

**Issue by coffee-squirrel** [pivotal-cf/docs-pcf-healthwatch#479]
Added @ https://github.com/pivotal-cf/docs-pcf-healthwatch/blob/f47f5d0efbf5ee721e373d10d6bff2423ec90009/release-notes.html.md.erb#L16

... and released: https://docs.pivotal.io/healthwatch/2-2/release-notes.html

... but not published at https://docs.pivotal.io/healthwatch/2-2/release-notes.html

**Comment by ograves-pivotal** [comment]
We manually released the HealthWatch v2.2.5 Release Notes on December 1. Closing.
